import { _, useEffect, useState } from "../../deps.ts";

const FETCH_DURATION = 1000;
const LEVEL_UP_DELAY = 6000;

const BASE_RESPONSE = {
  "data": {
    "seasonPass": {
      "id": "38771f80-bae9-11ec-a346-495417d4cba1",
      "orgId": "acd9d230-b9dd-11ec-bc90-7b62339255c4",
      "name": "Dev Season Pass",
      "daysRemaining": 190,
      "xp": { "count": "1", "__typename": "OrgUserCounter" },
      "levels": [{
        "levelNum": 1,
        "minXp": 1,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "0528f490-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzDab",
          "amountValue": null,
          "source": {
            "id": "0528f490-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzDab",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/0528f490-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "729837514881368097.png?size=600",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 18309,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzDab",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 2,
        "minXp": 3,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "31d78aa0-bae1-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "Dev emote pack #1",
          "amountValue": null,
          "source": {
            "id": "31d78aa0-bae1-11ec-bc90-7b62339255c4",
            "slug": "dev-random-emote-1",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/31d78aa0-bae1-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "ticket_merch.png",
                  "aspectRatio": 1,
                  "width": 512,
                  "height": 512,
                  "length": 10206,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "Random emote pack",
            "type": "redeemable",
            "targetType": "none",
            "ownedCollectible": { "count": 72, "__typename": "OwnedCollectible" },
            "data": {
              "description": "What emote will you get this time?!",
              "redeemType": "collectiblePack",
              "redeemData": {
                "collectibleRels": [{ "id": "6e2f6640-bae5-11ec-bc90-7b62339255c4", "odds": 0.5 }, {
                  "id": "73035c80-bae5-11ec-bc90-7b62339255c4",
                  "odds": 0.5,
                }],
              },
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 3,
        "minXp": 5,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "0e755390-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzCHOMP",
          "amountValue": null,
          "source": {
            "id": "0e755390-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzCHOMP",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/0e755390-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "695901707485577307.png?size=600",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 25868,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzCHOMP",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 4,
        "minXp": 7,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "11079730-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzPog",
          "amountValue": null,
          "source": {
            "id": "11079730-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzPog",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/11079730-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "713570412658819132.png?size=600",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 21552,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzPog",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 5,
        "minXp": 9,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "16426590-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzW",
          "amountValue": null,
          "source": {
            "id": "16426590-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzW",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/16426590-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "685947214526545979.png?size=600",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 18387,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzW",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 6,
        "minXp": 11,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "1a5ecba0-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzPDab",
          "amountValue": null,
          "source": {
            "id": "1a5ecba0-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzPDab",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/1a5ecba0-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "749416020447592539.gif?size=600",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 204617,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "gif",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzPDab",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 12, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 7,
        "minXp": 13,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "1f3b7470-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzU",
          "amountValue": null,
          "source": {
            "id": "1f3b7470-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzU",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/1f3b7470-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 20556,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzU",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 8,
        "minXp": 15,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "250b08c0-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzYESSIR",
          "amountValue": null,
          "source": {
            "id": "250b08c0-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzYESSIR",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/250b08c0-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 681657,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "gif",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzYESSIR",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 9,
        "minXp": 17,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "2f351d90-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzHehehe",
          "amountValue": null,
          "source": {
            "id": "2f351d90-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzHehehe",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/2f351d90-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 50849,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "gif",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzHehehe",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 10,
        "minXp": 19,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "35b7fc50-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzLaugh",
          "amountValue": null,
          "source": {
            "id": "35b7fc50-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzLaugh",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/35b7fc50-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 20573,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzLaugh",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 11,
        "minXp": 21,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "3a6fdf10-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzBeans",
          "amountValue": null,
          "source": {
            "id": "3a6fdf10-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzBeans",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/3a6fdf10-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 28607,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzBeans",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 21, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 12,
        "minXp": 23,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "3ea79550-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzHold",
          "amountValue": null,
          "source": {
            "id": "3ea79550-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzHold",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/3ea79550-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 26734,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzHold",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 13,
        "minXp": 25,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "43648120-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzCringe",
          "amountValue": null,
          "source": {
            "id": "43648120-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzCringe",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/43648120-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 16748,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzCringe",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 14,
        "minXp": 27,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "488cd8f0-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzChad",
          "amountValue": null,
          "source": {
            "id": "488cd8f0-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzChad",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/488cd8f0-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 9265,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzChad",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 15,
        "minXp": 29,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "4d9e4d60-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzGamer",
          "amountValue": null,
          "source": {
            "id": "4d9e4d60-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzGamer",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/4d9e4d60-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 21553,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzGamer",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 16,
        "minXp": 31,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "588ee680-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzD",
          "amountValue": null,
          "source": {
            "id": "588ee680-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzD",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/588ee680-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 18862,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzD",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 9, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 17,
        "minXp": 33,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "624ad030-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzL",
          "amountValue": null,
          "source": {
            "id": "624ad030-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzL",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/624ad030-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 22607,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzL",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 2, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 18,
        "minXp": 35,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "64949920-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzRage",
          "amountValue": null,
          "source": {
            "id": "64949920-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzRage",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/64949920-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 21215,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzRage",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 2, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 19,
        "minXp": 37,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "6a159840-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzMogul",
          "amountValue": null,
          "source": {
            "id": "6a159840-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzMogul",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/6a159840-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 20706,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzMogul",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }, {
        "levelNum": 20,
        "minXp": 39,
        "rewards": [{
          "sourceType": "collectible",
          "sourceId": "6e2f6640-bae5-11ec-bc90-7b62339255c4",
          "tierNum": 0,
          "description": "dStanzShoosh",
          "amountValue": null,
          "source": {
            "id": "6e2f6640-bae5-11ec-bc90-7b62339255c4",
            "slug": "dStanzShoosh",
            "fileRel": {
              "fileObj": {
                "cdn": "cdn.bio",
                "prefix": "collectible/6e2f6640-bae5-11ec-bc90-7b62339255c4",
                "data": {
                  "name": "3.0",
                  "aspectRatio": 1,
                  "width": 112,
                  "height": 112,
                  "length": 25165,
                },
                "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
                  "postfix": ".small",
                  "width": 128,
                  "height": 128,
                }, { "postfix": ".large", "width": 256, "height": 256 }],
                "ext": "png",
                "__typename": "File",
              },
              "__typename": "FileRel",
            },
            "name": "dStanzShoosh",
            "type": "emote",
            "targetType": "none",
            "ownedCollectible": { "count": 14, "__typename": "OwnedCollectible" },
            "data": {
              "description": null,
              "redeemType": null,
              "redeemData": null,
              "__typename": "CollectibleData",
            },
            "__typename": "Collectible",
          },
          "__typename": "SeasonPassLevelReward",
        }],
        "__typename": "SeasonPassLevel",
      }],
      "data": {
        "twitterUsers": [{
          "verified": false,
          "location": "Denver, CO",
          "entities": {
            "url": {
              "urls": [{
                "start": 0,
                "end": 23,
                "url": "https://t.co/E3X0U6CPJv",
                "expanded_url": "https://spore.build",
                "display_url": "spore.build",
              }],
            },
            "description": { "mentions": [{ "start": 11, "end": 22, "username": "truffleVIP" }] },
          },
          "description": "co-founder @truffleVIP",
          "name": "Riley",
          "id": "2238513584",
          "url": "https://t.co/E3X0U6CPJv",
          "profile_image_url":
            "https://pbs.twimg.com/profile_images/1455221700765831175/0Hd_vk9F_normal.jpg",
          "public_metrics": {
            "followers_count": 480,
            "following_count": 478,
            "tweet_count": 2531,
            "listed_count": 6,
          },
          "username": "riley_miller00",
        }],
        "twitchChannelIds": ["484831439"],
        "discordGuildIds": ["401900786080022548"],
      },
      "seasonPassProgression": {
        "tierNum": 0,
        "changesSinceLastViewed": [],
        "__typename": "SeasonPassProgression",
      },
      "__typename": "SeasonPass",
    },
  },
  "extensions": { "components": {} },
};

const SAMPLE_CHANGE = {
  "levelNum": 1,
  "rewards": [{
    "sourceType": "collectible",
    "sourceId": "0528f490-bae5-11ec-bc90-7b62339255c4",
    "tierNum": 0,
    "description": "dStanzDab",
    "amountValue": null,
    "source": {
      "id": "0528f490-bae5-11ec-bc90-7b62339255c4",
      "slug": "dStanzDab",
      "fileRel": {
        "fileObj": {
          "cdn": "cdn.bio",
          "prefix": "collectible/0528f490-bae5-11ec-bc90-7b62339255c4",
          "data": {
            "name": "729837514881368097.png?size=600",
            "aspectRatio": 1,
            "width": 112,
            "height": 112,
            "length": 18309,
          },
          "variations": [{ "postfix": ".tiny", "width": 32, "height": 32 }, {
            "postfix": ".small",
            "width": 128,
            "height": 128,
          }, { "postfix": ".large", "width": 256, "height": 256 }],
          "ext": "png",
          "__typename": "File",
        },
        "__typename": "FileRel",
      },
      "name": "dStanzDab",
      "type": "emote",
      "targetType": "none",
      "ownedCollectible": { "count": 1, "__typename": "OwnedCollectible" },
      "data": {
        "description": null,
        "redeemType": null,
        "redeemData": null,
        "__typename": "CollectibleData",
      },
      "__typename": "Collectible",
    },
    "__typename": "SeasonPassLevelReward",
  }],
  "__typename": "SeasonPassLevel",
};

export function useTestSeasonPassData() {
  const [data, setData] = useState();
  const [fetching, setFetching] = useState(true);
  const [error, setError] = useState();

  // simulate fetching
  useEffect(() => {
    setTimeout(() => {
      setData(BASE_RESPONSE.data);
      setFetching(false);

      // simulate leveling up
      setTimeout(() => {
        console.log("leveling up season pass");
        const newData: typeof BASE_RESPONSE = _.cloneDeep(BASE_RESPONSE);
        newData.data.seasonPass.xp.count = "4";
        newData.data.seasonPass.seasonPassProgression.changesSinceLastViewed.push(
          SAMPLE_CHANGE as never,
        );
        console.log(newData);
        setData(newData.data);
      }, LEVEL_UP_DELAY);
    }, FETCH_DURATION);
  }, []);

  return { data, fetching, error };
}
